### ISSUE TITLE
Home page menu bar styling

### ISSUE THREAD

**Issue by derekadams** [sitewhere/community-documentation#20]
There are some minor menu bar styling updates on the home page (internal site menu bar looks good). The following updates will help the items look more uniform and consistent:

- [x] We may want to update the default font. I disabled the existing font in the example.
- [x] Make all menu items a medium bold for better readability.
- [x] Have a minimum width for menu items to ensure spacing.
- [x] Add margins for dropdown elements to align them vertically with other elements.
- [x] Update `Enterprise` element to add left margin and use button background rather than link to make it stand out.
- [x] Update the logo
Here is an example of the updates based on making local CSS changes in the browser:

![image](https://user-images.githubusercontent.com/338921/109996493-490ae700-7cdd-11eb-9e6b-cbd2f183e396.png)

**Comment by derekadams** [comment]
Also, we can update the logo to use an SVG image without the tagline so it's more readable. I think this one should work:
https://sitewhere-web.s3.amazonaws.com/logos/4.COLOR+BOLD+FONT+H.svg

**Comment by fferz** [comment]
Regarding the fonts.. If we desactivate the menu fonts, the font family used is 'Open Sans'.. Is this the font you like? Which font would you like to use?
![imagen](https://user-images.githubusercontent.com/3790709/110004567-584a5e80-7cf6-11eb-9559-30ae3d0f9f59.png)

**Comment by derekadams** [comment]
@fferz Yes, we can use Open Sans for now. The only reason I think it's needed is that the existing font doesn't seem to handle more font weight. I increased it to `500` on the menu fonts, but it caused artifacts in the characters.
